version: 2

jobs:
  build:
    working_directory: ~/cbs.com

    docker:
      - image: node:7

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Run tests
          command: yarn test

      - save_cache:
          key: yarn
          paths:
            - ~/.yarn
