version: 2

jobs:
  build:
    working_directory: ~/cbs.com

    docker:
      - image: node:7

    steps:
      - checkout

      - restore_cache:
          keys:
            - cbs-{{ .Branch }}-{{ checksum "package.json" }}
            - cbs-{{ .Branch }}
            - cbs-master-{{ checksum "package.json" }}
            - cbs-master

      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Run tests
          command: yarn test

      - save_cache:
          key: cbs-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.yarn
            - ~/cbs.com/node_modules

      - deploy:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn build && yarn deploy -- --token "$FIREBASE_TOKEN"
            fi
