version: 2

jobs:
  test:
    working_directory: ~/cbs.com

    docker:
      - image: node:8

    steps:
      - checkout

      - restore_cache:
          keys:
            - cbs-{{ .Branch }}-{{ checksum "package.json" }}
            - cbs-{{ .Branch }}
            - cbs-master-{{ checksum "package.json" }}
            - cbs-master

      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Run tests
          command: yarn test

      - save_cache:
          key: cbs-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.yarn
            - ~/cbs.com/node_modules

  deploy:
    working_directory: ~/cbs.com

    docker:
      - image: node:8

    steps:
      - checkout

      - restore_cache:
          keys:
            - cbs-{{ .Branch }}-{{ checksum "package.json" }}
            - cbs-{{ .Branch }}
            - cbs-master-{{ checksum "package.json" }}
            - cbs-master

      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Build
          command: yarn build

      - deploy:
          name: Deploy
          command: yarn deploy --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  stack:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
