---


articles:

  - title: Hit the ground running at Appear Here
    slug: appearhere
    description: Creating an inclusive, transparent and collaborative user experience process is the most efficient way to build an user-centred team.
    role: Research, interaction design, information architecture, interface design, prototyping, ux management
    team: Product manager, product designer, 5 developers
    duration: 3 months starting end of July 2017
    contentFile: appearhere.pug
    more:
      - 15 minutes read

  - title: Connecting fanboys with Zenitth
    slug: zenitth
    description: Did you know that some people are crazy in love with… brands? Discover how Zenitth brought them together for a legendary fight!
    role: Research, information architecture, interface, prototyping, pitch
    team: Céline, Adrien, Jeremy, Oliver, Samuel, Arnaud, Alexis
    duration: 11 days in July 2015
    contentFile: zenitth.pug
    more:
      - 16 minutes read

  - title: Empowering night owl duos with Tchiiiin
    slug: tchiiiin
    description: Discover Tchiiiin, a SoLoMo (social, local, mobile) iOS application for clubbers who dream of an unforgettable night.
    role: Research, information architecture, interface, visual design, prototyping
    team: Charles, Harold, Nicolas
    duration: 6 days in February 2015
    contentFile: tchiiiin.pug
    more:
      - 8 minutes read

  - title: Disrupting sight games with Captain Sight
    slug: captainsight
    description: 48h to create Smart Watch applications to change the everyday life of glasses wearers? Challenge accepted! Introducing CaptainSight…
    role: Research, information architecture, interface, visual design, pitch
    team: Emmanuel, Loïc, Sebastien
    duration: 48h in June 2015
    contentFile: captainsight.pug
    more:
      - 4 minutes read

  - title: Connecting travellers and locals with Welcom’
    slug: welcom
    description: Discover Welcom’, the project I worked on for Hack4Europe, a 6 months online hackathon with more than 300 participants from 5 different countries.
    role: Research, information architecture, interface, visual design, prototyping, front-end development, pitch
    team: Jean-Baptise, Julien, Robin, Tanguy
    duration: Dozens of nights between July 2015 and March 2016
    contentFile: welcom.pug
    more:
      - 16 minutes read


about:

  education:

    - title: "Project Management and User Experience"
      subtitle: "IESA Multimedia, alternating with Agorize – Paris, France"
      description: "Courses: project management, user experience design, copywriting, sensory marketing, digital knowledge, interaction design, user interface design, wireframing, prototyping, data mining, business model."
      more:
        - From 2014 to 2015
        - 3rd year of Bachelor's Degree (2nd year skipped)

    - title: "Front End Development and Webdesign"
      subtitle: "Fonderie de l'image, alternating with Toxicode – Paris, France"
      description: "Courses: web design, front end development (HTML, CSS), programming (javascript), motion design."
      more:
        - From 2013 to 2014
        - 1st year of Bachelor's Degree

    - title: "Design and Applied Arts"
      subtitle: "Ecole Boulle – Paris, France"
      description: "Courses: use case, applied research, technical art and civilization (history of art), fundamental plastic expression, technical plans, conventional representation of the image, design creation and design culture."
      more:
        - From 2009 to 2012
        - 3 years of High School
