---


articles:

  - title: Connecting fanboys with Zenitth
    slug: zenitth
    description: Did you know that some people are crazy in love with… brands? Discover how Zenitth brought them together for a legendary fight!
    role: Research, information architecture, interface, prototyping, pitch
    team: Céline, Adrien, Jeremy, Oliver, Samuel, Arnaud, Alexis
    duration: 11 days in July 2015
    contentFile: zenitth.pug
    more:
      - 16 minutes read

  - title: Empowering night owl duos with Tchiiiin
    slug: tchiiiin
    description: Discover Tchiiiin, a SoLoMo (social, local, mobile) iOS application for clubbers who dream of an unforgettable night.
    role: Research, information architecture, interface, visual design, prototyping
    team: Charles, Harold, Nicolas
    duration: 6 days in February 2015
    contentFile: tchiiiin.pug
    more:
      - 8 minutes read

  - title: Disrupting sight games with Captain Sight
    slug: captainsight
    description: 48h to create Smart Watch applications to change the everyday life of glasses wearers? Challenge accepted! Introducing CaptainSight…
    role: Research, information architecture, interface, visual design, pitch
    team: Emmanuel, Loïc, Sebastien
    duration: 48h in June 2015
    contentFile: captainsight.pug
    more:
      - 4 minutes read

  - title: Connecting travellers and locals with Welcom’
    slug: welcom
    description: Discover Welcom’, the project I worked on for Hack4Europe, a 6 months online hackathon with more than 300 participants from 5 different countries.
    role: Research, information architecture, interface, visual design, prototyping, front-end development, pitch
    team: Jean-Baptise, Julien, Robin, Tanguy
    duration: Dozens of nights between July 2015 and March 2016
    contentFile: welcom.pug
    more:
      - 16 minutes read


about:

  education:

    - title: "Project Management and User Experience"
      subtitle: "IESA Multimedia, alternating with Agorize – Paris, France"
      description: "Courses: project management, user experience design, copywriting, sensory marketing, digital knowledge, interaction design, user interface design, wireframing, prototyping, data mining, business model."
      more:
        - From 2014 to 2015
        - 3rd year of Bachelor's Degree (2nd year skipped)

    - title: "Front End Development and Webdesign"
      subtitle: "Fonderie de l'image, alternating with Toxicode – Paris, France"
      description: "Courses: web design, front end development (HTML, CSS), programming (javascript), motion design."
      more:
        - From 2013 to 2014
        - 1st year of Bachelor's Degree

    - title: "Design and Applied Arts"
      subtitle: "Ecole Boulle – Paris, France"
      description: "Courses: use case, applied research, technical art and civilization (history of art), fundamental plastic expression, technical plans, conventional representation of the image, design creation and design culture."
      more:
        - From 2009 to 2012
        - 3 years of High School

  experiences:

    - title: "Head of User Experience"
      subtitle: "Enki Labs Inc. – London, United Kingdom"
      description: "Enki is a mobile app, with more than 200k users, which provides content to help developers improve their skills on a daily basis. My job is to advocate for the user and the user experience process. I am primarily in charge of the research, information architecture, user interface, prototyping, visual design and data analysis. I also act as a product owner for some of our features: writing specifications, priorisation and product management. I also help to improve our management tools and processes. Finally, I am responsible for the planning of team building events: organisation of parties (bi-weekly) and ski trip (yearly)."
      more:
        - From March 2016 – Full time – Current position
        - Startup – Less than 10 employees

    - title: "UX Teacher"
      subtitle: "Le Wagon – Paris, France"
      description: "Le Wagon is an unconventional school to learn to code in Ruby. Every session brings together passionate people from various industries, often looking to reinvent themselves. As a UX Teacher, I guide students during their final project to help them build the product they dreamed of. I introduce them to user experience methods and organize workshops tailored to each team according to their level of progress."
      more:
        - From April 2015 – Occasionally
        - School – 20-30 students

    - title: "UX Designer"
      subtitle: "Theodo – Paris, France"
      description: "Theodo is a famous agile tech agency working with startups and large companies. As the first designer in the company, I had to find solutions to implement UX methods in the Theodo agile development process as well as introducing/selling UX to our clients. While working on project, I used all my design skills: user research, information architecture, user interfaces, visual design, prototyping and front end development. I was also in charge of some of the team building events (cinema nights, Christmas party) and internal communication (branded hoodies, powerpoint presentations)."
      more:
        - From November 2015 to March 2016 – Full time
        - Agency – More than 80 employees

    - title: "UX/UI Designer and Front End Developer"
      subtitle: "Freelance – Paris, France"
      description: "Some of my missions: establishment of UX processes in agile projects, iterations on an MVP, introduction to UX Design and projects support, ergonomy and PAO for a software dedicated to jurists and lawyers, visual identity, teaser websites."
      more:
        - From May 2015 to November 2015 – Full time
        - 7+ clients

    - title: "UX Designer"
      subtitle: "Agorize – Paris, France"
      description: "Agorize is an innovation challenge platform which bring online thousands of students, developers and startups. I worked for Agorise part-time, alternating with IESA Multimedia where I was enrolled as an UX student. I was in charge of user experience for both our public and private platforms. I was the only UX designer for the first 6 months and worked closely with the CEO to define new features and re-design old ones. I applied user research methods, improved the information architecture and designed interfaces."
      more:
        - From september 2014 to May 2015 – Part time
        - Startup – Less than 80 employees

    - title: "UI Designer and Front End Developer"
      subtitle: "Toxicode – Paris, France"
      description: "Toxicode is a small company divided in two side: agency and research/development. I worked part-time alternating with Fonderie de l'image where I was studying front-end development and web design. This was my first experience as a front-end developer: I learned to code in HTML, CSS and JavaScript. I worked closely with developers to create education games. I imagined and designed many games as well as digital solutions for our clients (mainly e-commerce)."
      more:
        - From September 2013 to August 2014 – Part time
        - Agency – Less than 10 employees
