---

articles:
  - title: Connecting fanboys with Zenitth
    slug: zenitth
    description: Learn how I used research, information architecture, interface, and prototyping in order to build my final year product.
    contentFile: zenitth.pug

cv:
  education:
    - title: School one
      subtitle: Enki Labs - London
      description: Blah blah blah
      more:
        - From sept to Jan
        - Company size

  experiences:
    - title: Head of UX at Enki
      subtitle: Enki Labs - London
      description: Blah blah blah
      more:
        - From sept to Jan
        - Company size
