version: 2

jobs:
  test-v1:
    working_directory: ~/cbs.com/v1

    docker:
      - image: node:8

    steps:
      - checkout:
          path: ~/cbs.com

      - restore_cache:
          keys:
            - cbs-v1-{{ .Branch }}-{{ checksum "package.json" }}
            - cbs-v1-{{ .Branch }}
            - cbs-v1-master

      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Run tests
          command: yarn test

      - save_cache:
          key: cbs-v1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.yarn
            - ~/cbs.com/v1/node_modules

  test-v2:
    working_directory: ~/cbs.com/v2

    docker:
      - image: node:18

    steps:
      - checkout:
          path: ~/cbs.com

      - restore_cache:
          keys:
            - cbs-v2-{{ .Branch }}-{{ checksum "package.json" }}
            - cbs-v2-{{ .Branch }}
            - cbs-v2-master

      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Build
          command: yarn build

      - save_cache:
          key: cbs-v2-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.yarn
            - ~/cbs.com/v2/node_modules

workflows:
  version: 2
  stack:
    jobs:
      - test-v1
      - test-v2
