---


articles:

  - title: Helping travellers pack with Wanderlist
    slug: wanderlist
    description: Travelling somewhere? Don’t forget your toothbrush. Wanderlist offers pre-defined checklists to help you pack for your trips.
    role: NA
    team: NA
    duration: NA
    contentFile: wanderlist.pug
    more:
      - Project introduction
      - 2 min read

  - title: Getting tasks done with Trello Air
    slug: trelloair
    description: Trello Air is a theme for Trello.com which reduces clutter and provides more efficient visual cues to help you get things done.
    role: NA
    team: NA
    duration: NA
    contentFile: trelloair.pug
    more:
      - Project introduction
      - 2 min read

  - title: Making mortgages simple at Trussle
    slug: trussle
    description: The story behind some of the design projects I led at Trussle which increasing conversion and satisfaction rates.
    role: NA
    team: NA
    duration: NA
    contentFile: trussle.pug
    more:
      - Case study
      - 5 min read

  - title: Kickstarting projects with research methods
    slug: userresearch
    description: Understanding your users' behaviors, needs and motivations is key to design kickass experiences.
    role: NA
    team: NA
    duration: NA
    contentFile: userresearch.pug
    more:
      - Talk, 60+ attendees
      - 60 min read

  - title: Hitting the ground running at Appear Here
    slug: appearhere
    description: Find out how I created an inclusive, transparent and collaborative user experience process.
    role: NA
    team: NA
    duration: NA
    contentFile: appearhere.pug
    more:
      - Case study
      - 10 min read

  - title: Connecting fanboys with Zenitth
    slug: zenitth
    description: Did you know that some people are crazy in love with brands? Introducing Zenitth.
    role: NA
    team: NA
    duration: NA
    contentFile: zenitth.pug
    more:
      - Case study
      - 20 min read

  - title: Empowering night owl duos with Tchiiiin
    slug: tchiiiin
    description: Discover Tchiiiin, a SoLoMo (social, local, mobile) iOS application for clubbers who dream of an unforgettable night.
    role: NA
    team: NA
    duration: NA
    contentFile: tchiiiin.pug
    more:
      - Case study
      - 15 min read

  - title: Disrupting sight games with Captain Sight
    slug: captainsight
    description: 48h to create Smart Watch applications to change the everyday life of glasses wearers? Challenge accepted!
    role: NA
    team: NA
    duration: NA
    contentFile: captainsight.pug
    more:
      - Case study
      - 5 min read

  - title: Connecting travellers and locals with Welcom’
    slug: welcom
    description: Welcom' was created during a 6 months online hackathon with more than 300 participants from 5 different countries.
    role: NA
    team: NA
    duration: NA
    contentFile: welcom.pug
    more:
      - Case study
      - 15 min read


about:

  education:

    - title: "Project Management and User Experience"
      subtitle: "IESA Multimedia, alternating with Agorize – Paris, France"
      description: "Courses: project management, user experience design, copywriting, sensory marketing, digital knowledge, interaction design, user interface design, wireframing, prototyping, data mining, business model."
      more:
        - From 2014 to 2015
        - 3rd year of Bachelor's Degree (2nd year skipped)

    - title: "Front End Development and Webdesign"
      subtitle: "Fonderie de l'image, alternating with Toxicode – Paris, France"
      description: "Courses: web design, front end development (HTML, CSS), programming (javascript), motion design."
      more:
        - From 2013 to 2014
        - 1st year of Bachelor's Degree

    - title: "Design and Applied Arts"
      subtitle: "Ecole Boulle – Paris, France"
      description: "Courses: use case, applied research, technical art and civilization (history of art), fundamental plastic expression, technical plans, conventional representation of the image, design creation and design culture."
      more:
        - From 2009 to 2012
        - 3 years of High School
